name: tutorial-py38
channels:
  - conda-forge  #defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - pyyaml
  - jupyter
  - matplotlib
  - pip:
    - joblib